name: CI/CD Pipeline with Docker Deploy

on:
  push:
    branches: [ "master" ]
    paths: ["Dockerfile",".github/workflows/ci-cd.yml"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest test_main.py

  build-and-push:
    runs-on: ubuntu-latest
    # Docker Hub tag
    env:
      IMAGE_NAME: jupyter-book-gh
      IMAGE_VERSION: latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to DockerHub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        echo "${{secrets.DOCKER_USER}}/$IMAGE_NAME:$IMAGE_VERSION"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/$IMAGE_NAME:$IMAGE_VERSION
    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_USER}}/$IMAGE_NAME:$IMAGE_VERSION

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub (for deploy)
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Deploy to Docker Host
        run: |
          docker pull docker.pkg.github.com/ivanovspb/cdci/my-python-app:latest
          docker stop my-running-app || true
          docker rm my-running-app || true
          docker run -d -p 8000:8000 --name my-running-app docker.pkg.github.com/ivanovspb/cdci/my-python-app:latest
