name: CI/CD Pipeline with Docker Deploy

on:
  push:
    branches:
      - main  # Use main instead of master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest test_main.py

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Correct checkout

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v2/
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build image
        run: |
          docker build -t ${{ github.repository }}:${{ env.IMAGE_TAG }} .
          
      - name: Tag Image
          # Added step to tag the image with the correct name
          run: docker tag ${{ github.repository }}:${{ env.IMAGE_TAG }} docker.pkg.github.com/${{ github.repository }}:${{ env.IMAGE_TAG }}
      - name: Push to Docker registry
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}:${{ env.IMAGE_TAG }}


  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image
    environment:
      name: production # Important for consistency
      url: https://example.com # Replace with your URL
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Docker Host
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull docker.pkg.github.com/${{ github.repository }}:${{ env.IMAGE_TAG }}  # Correct docker repo
            docker stop my-running-app || true
            docker rm my-running-app || true
            docker run -d -p 8000:8000 --name my-running-app docker.pkg.github.com/${{ github.repository }}:${{ env.IMAGE_TAG }}
          
      - name: Set IMAGE_TAG
        id: set-tag
        run: echo "::set-output name=IMAGE_TAG::$(echo ${{ github.sha }})"
      
      - name: Set Environment Variables
        run: echo "::set-output name=IMAGE_TAG::$(step.set-tag.outputs.IMAGE_TAG)"
        id: set-tag
