name: CI/CD Pipeline with Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest test_main.py

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t my-python-app:latest .

      - name: Login to Docker Hub (optional, for pushing to a registry)
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com #or your preferred registry
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to registry
        run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/my-python-app:latest
        if: always() # Always push even if there are failures in previous steps (for debugging purposes)


  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Login to your server (or kubernetes cluster)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/my-python-app:latest
            docker stop my-running-app || true  # Stop existing container if it exists.
            docker rm my-running-app || true
            docker run -d -p 8000:8000 --name my-running-app docker.pkg.github.com/$GITHUB_REPOSITORY/my-python-app:latest
